### PR TITLE
Add new build script

### PR DESCRIPTION
**Pull request by zimsneexh**
Add a build.sh script to replace the Makefile. The new script calls "security" to unlock the keychain which is required to build in an SSH shell.

### CODE REVIEW

**Review by maxkofler — APPROVED** [review]
Looks fine to me

**Comment by zimsneexh** [comment]
I'll leave merging it to rfb up to you as its your branch.

**Comment by maxkofler** [comment]
Are you sure you couldn't rebase this branch on `main`? I would do that, merge it into `main` and rebase `rfb` on that. This would lead to a cleaner workflow.

**Comment by zimsneexh** [comment]
Sure, that's fine by me. I can rebase my branch on main and open another PR

**Comment by maxkofler** [comment]
You can just rebase and force push onto this branch, that should update the PR I think

**Pull request closed without merging**
