### PR TITLE
Merge 'manager' into 'main'

### PR DESCRIPTION
**Pull request by maxkofler**
This PR proposes the following features for merge into `main`:
- API: `/m` endpoints for managing media
- API: `/v` endpoints for managing virtual machines
- Removal of the old `vrfb` code to make space for the new RFB code
- Virtual machine creation and management

### CODE REVIEW

**Comment by maxkofler** [comment]
Additionally, I would suggest the following branches for deletion:
- `api`: Its code is contained within this PR
- `cleanup`: Its code is contained within this PR
- `fixes`: The `import System` fix has been cherry-picked into this PR

**Review by zimsneexh — APPROVED** [review]
Code and docs look good. Since these commits contain quite a bit of cleanup I would also remove manager/velocity/api/APITest.py since its probably incompatible with the current api anyway.

One more thing: We should probably change the Copyright header to ".. (C) Velocity contributors", which is more fitting imo.

Edit: Removing `api`, `cleanup` and `fixes` is fine.

**Comment by maxkofler** [comment]
I agree with both of your points, I will perform those changes and merge the pull request

**Comment by maxkofler** [comment]
I will replace the copyright headers in a separate branch, this should be a separate action IMO

**Pull request merged**
