### PR TITLE
Merge bulk of /v into api

### PR DESCRIPTION
**Pull request by maxkofler**
This pull request merges the bulk of the `/v` namespace into the `api` branch to provide the functionality to other modules

### CODE REVIEW

**Comment by maxkofler** [comment]
I merged this locally and the build was fine, so merging this should not be a problem

**Review by zimsneexh — COMMENTED** [review]
Code is fine - Is "virtualization/" still needed or is it all dead code now? If it is I would prefer to remove it first, along with httpserver.swift and manager.swift since those are unneeded now.

**Comment by maxkofler** [comment]
Yes, they currently are dead. My plan is to replace the contents of /virtualization with a core manager class that the API can dispatch commands (start,stop...) to. But removing the old stuff prior to creating new stuff is good. My approach to that would be to merge the `api_v` stuff into `api` and then rip out the old stuff in a new branch, because I think it will require some tinkering...

**Review by zimsneexh — APPROVED** [review]
Sounds good. Fine to merge

**Pull request merged**
